### ISSUE TITLE
Question about ServerAdmin in httpd?

### ISSUE THREAD

**Issue by odunybrad** [setiseta/docker-wordpress#1]
Thanks for providing the container! 

I am doing a research aiming at finding issues in configuration files. After pulling the image we notice that `ServerAdmin` is set to `webmaster@localhost` in `/etc/apache2/sites-enabled/000-default.conf`.  

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#servername) recommends the following config:
*  `ServerAdmin`: "However, it's recommended to actually use an email address, since there are a lot of CGI scripts that make that assumption. "

Could you please provide a knob to specify the value of `ServerAdmin`?

**Comment by setiseta** [comment]
Thank you for the request.
Since this is just an extend of the official worpress docker, with the zip module enabled, you should post your request on the official repository.
As the zip module is also enabled in the official repository now, you should stay with the official image: https://hub.docker.com/_/wordpress

At least i don't think it is needed, that there is any change on the image itself, it don't look like there is a logic on the file: /etc/apache2/sites-enabled/000-default.conf
so you can just mount your copy of the file to the location, edit it to your needs and restart the container.
